name: Production

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  docker_build:
    name: Docker Build, Push and Release a Docker container to Heroku. 
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build, Push and Release a Docker container to Heroku. 
      uses: gonuit/heroku-docker-deploy@v1.3.3 
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        dockerfile_directory: ./
        dockerfile_name: Dockerfile
        docker_options: "--no-cache"
        process_type: web