name: QA Response

on:
  push:
    branches: [ QA ]
  pull_request:
    branches: [ QA ]

jobs:
  response:
    runs-on: ubuntu-latest
    message:
      - run: |
          output=$(python3 qa.py)
          echo echo "::set-output name=response::$output"
        id: message
      - if: message.message.outputs.response == "NO"
        run: exit "QA wont let the app pass the quality check"


    


  merge:
    runs-on: ubuntu-latest
    needs: response

    - name: Merge branch 'QA' -> 'production'
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        from_branch: QA
        target_branch: production
        github_token: ${{ secrets.GHUB_TOKEN }}
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: QA Phase passed
        branch: production
  

